@baseUrl=https://localhost:3000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbTNiNWp6ZWQwMDAwZDF5c2o3MmN4YXJqIiwiaWF0IjoxNzMxMjE4MzQxLCJleHAiOjE3MzEyMTg2NDF9.Py6IzIJX7cX0yrsBFOXA4CLa3TSDV4J4e5b3KeIorSQ

# ENDPOINTS AUTENTICAÇÃO

### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### REVOGAR TOKEN
POST {{baseUrl}}/revoke-refresh-tokens
Content-Type: application/json

{
  "userId": 1
}

#ENDPOINTS DE USUÁRIO

### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123",
  "nome": "John Doe"
}

# ENDPOINTS DE LICITAÇÃO

### Criar Licitação
POST {{baseUrl}}/licitacao/criar-licitacao
#Content-Type: multipart/form-data
Content-Type: application/json
Authorization:{{token}}

{
  "tituloLicitacao": "Licitacao de Teste",
  "descricaoLicitacao": "Descrição detalhada da licitação",
  "dataInicio": "2024-11-09T10:00:00Z",
  "dataInicioCandidaturas": "2024-11-10T09:00:00Z",
  "dataFimCandidaturas": "2024-11-20T17:00:00Z",
  "hashEdital": "hash-edital",
  "hashETP": "hash-etp"
}

# --form-data; name="etp"; filename="etp.pdf"
# < ./files/documents/dummy.pdf
# --form-data; name="edital"; filename="edital.pdf"
# < ./files/documents/dummy.pdf



### Detalhes
GET {{baseUrl}}/a
Content-Type: application/json

