version: "3"
services:
    ipfs:
        image: ipfs/kubo:latest
        environment:
            - IPFS_PROFILE=server
            - IPFS_PATH=/ipfsdata
        volumes:
            - ./data/ipfs:/ipfsdata:Z
            - ./start-ipfs.sh:/start-ipfs.sh:Z
        ports:
            - "4001:4001"
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:8081:8081"
            - "127.0.0.1:5001:5001"
        entrypoint: ["/start-ipfs.sh"]
